services:
  ros_gz_nav2:
    build:
      context: ../../
      dockerfile: src/wheeltec_mini_mec_gz_sim/Dockerfile
      args:
        - USERNAME=${USER:-user}
        - USER_UID=${UID:-1000}
        - USER_GID=${GID:-1000}
    image: ros_gz_nav2
    container_name: wheeltec_mini_mec_ws
    shm_size: "4gb"
    stdin_open: true
    tty: true
    network_mode: host
    ipc: host
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu, graphics, utility, display]
    environment:
      - DISPLAY=${DISPLAY}
      - XAUTHORITY=/home/${USER:-user}/.Xauthority
      - QT_X11_NO_MITSHM=1
    volumes:
      - ../../src:/home/${USER:-user}/ros2_ws/src
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ${XAUTHORITY}:/home/${USER:-user}/.Xauthority
